### ISSUE TITLE
After minimizing search pane: no way to get it back

### ISSUE THREAD

**Issue by pdfkungfoo** [adamreichold/QMediathekView#13]
Maybe I'm too stupid to understand the app -- however, here's my problem: I played only 2 minutes with it and already love it... but I accidentally closed (or minimized) the "search" panel, and now I don't find a way to get it back.

**Update.** I should have added this, maybe: I'm using the AppImage release. Maybe there is something missing -- because I cannot identify any menu giving me access to some "prefererence" settings.

**Comment by adamreichold** [comment]
Hello Kurt and thank you for taking the time to report this. I guess you and @probonopd are the first users of this application besides myself and this is just a usability bug as these panes should not be closable at all. Will try to create a fix ASAP...

**Comment by adamreichold** [comment]
(You should be able to get it back by deleting `~/.config/QMediathekView/QMediathekView.conf` for now.)

**Comment by pdfkungfoo** [comment]
I had "fixed" it myself just before reading your comment (thanks for the super-fast reaction). I had just removed the line 

     mainWindowGeometry=

from the `.conf` file.
