### ISSUE TITLE
Use Interactive ResizeMode and save/restore QHeaderView state

### ISSUE THREAD

**Issue by ghost** [adamreichold/QMediathekView#14]
Hi, I've been using QMediathekView for a while and build from git master all the time. Generally I'm loving all the recently introduced changes/migrations (thanks for those), but I have noticed the default column widths are a bit sub-optimal for me. Looking at the [code](https://github.com/adamreichold/QMediathekView/blob/master/mainwindow.cpp#L107), it is the **Topic** column that basically decides the layout:

```
m_tableView->horizontalHeader()->setSectionResizeMode(QHeaderView::ResizeToContents);
m_tableView->horizontalHeader()->setSectionResizeMode(2, QHeaderView::Stretch);
```

For most channels this looks great, less so for _HR_ and _ZDF_ (my preferred channel), which have rather wide **Topic** items, making the **Title** less readable. I've tried to rectify this by setting ResizeMode to Interactive (user resizable) and dropping the Stretch on the second (**Topic**) column:

`m_tableView->horizontalHeader()->setSectionResizeMode(QHeaderView::Interactive);`

This works out better for me, but I'm having trouble integrating [save/restore functionality for the QHeaderView state](https://forum.qt.io/topic/27897/solved-qheaderview-savestate-and-restorestate-example/3). I'm not suggesting to change the defaults, just asking for some pointers on how to achieve the latter, if at all possible.

Regards

**Comment by adamreichold** [comment]
Thank you for taking the time to report this!

> Looking at the code, it is the Topic column that basically decides the layout:

This is the right in the code but the section index is zero-based, so it is the third column title which is stretched to fill the available space whereas the others a resized according to content with the idea being that everything but the title is short, but as you point out this is not universally correct.

Ideally, something like enlarge-until-content-fits-and-then-stretch-to-fill-the-remaining-space would be available for the section resize mode.

> I'm not suggesting to change the defaults, just asking for some pointers on how to achieve the latter, if at all possible.

I am actually very open to changing to better working defaults and will look into the save/restore functionality. Will report back here when I had time to test this a bit. (It might also work to give the channel and topic columns maximum widths for example, so they cannot make the title less readable.)

**Comment by adamreichold** [comment]
I just pushed a small change to `master` that limits the maximum column width for everything but the title column (as it is stretching) so that long topics should not make this column less readable anymore. Could you give this a try?

I am still trying to figure out how to integrate interactive resizing. I am not sure if an explicit setting is appropriate or whether it should just switch to interactive resizing if the user starts to resize things?

**Comment by adamreichold** [comment]
> Hi, I've been using QMediathekView for a while and build from git master all the time.

Just out of curiosity: the introduction of the Rust components worked out for you?

**Comment by adamreichold** [comment]
I also pushed a branch unconditionally enabling interactive resize mode and saving/restoring the header state: [use-interactive-column-resize](https://github.com/adamreichold/QMediathekView/tree/use-interactive-column-resize).

**Comment by ghost** [comment]
> Just out of curiosity: the introduction of the Rust components worked out for you?

They did yes. Aside from the column width issue QMediathekView feels more responsive. No errors/warnings reported. Tested extensively on GNOME Wayland/Xwayland (Arch Linux) and on GNOME Xorg (Ubuntu 16.04 LTS).

I'll be happy to test both git master and the use-interactive-column-resize branch. Building now, will report back soon. Thank you for looking into it.

**Comment by ghost** [comment]
[UPDATE] here are my observations after building/testing both branches:

**git#branch=master**
```
- builds cleanly;
- runs cleanly on Xwayland;
- Wayland reports:
    'qt.qpa.wayland: Non-toplevel surfaces can't request window states'
    (to be expected);
- column width issues fixed;
- resizing working smoothly;
- works 10/10 for me here.
```

**git#branch=use-interactive-column-resize**
```
- builds cleanly;
- runs cleanly on Xwayland;
- Wayland reports:
    'qt.qpa.wayland: Non-toplevel surfaces can't request window states'
    'qt.qpa.wayland: Wayland does not support QWindow::requestActivate()'
    (to be expected);
- column width issues fixed;
- resizing working smoothly;
- save/restore functionality working as expected;
- works 10/10 for me here;
- my personal favorite!
```

All in all a fine piece of work, very much appreciated. On a side-note, after recent dependency-reducing commits, I think you can safely drop _boost_ and _xz_ from depends array in [qmediathekview-git](https://aur.archlinux.org/packages/qmediathekview-git/) and add _rust_ to its makedepends array. Going to enjoy a few Tatort episodes :)

Regards

**Comment by adamreichold** [comment]
> On a side-note, after recent dependency-reducing commits, I think you can safely drop boost and xz from depends array in qmediathekview-git and add rust to its makedepends array.

Did that but I admittedly do not have an Arch system around and even though it did start to build in a container, I would be glad if you could verify that the adjusted `PKGBUILD` works as expected.

**Comment by adamreichold** [comment]
> - my personal favorite!

I am still wondering whether I switch the default to user resizing, whether to make this configurable or whether to change nothing at all to keep it as simple as possible?

**Comment by ghost** [comment]
> Did that but I admittedly do not have an Arch system around and even though it did start to build in a container, I would be glad if you could verify that the adjusted PKGBUILD works as expected.

I had already removed the redundant packages from qmediathekview-git when reporting back earlier. So yes, I can **confirm** the adjusted PKGBUILD is working fine on Arch. One nitpick: marking `both` _cargo_ and _rust_ as makedepends is redundant, either one of those will do. Personally I'd go for _rust_, as that replaces cargo in the Arch repositories.

> I am still wondering whether I switch the default to user resizing, whether to make this configurable or whether to change nothing at all to keep it as simple as possible?

I can see how implementing the `use-interactive-column-resize` branch as default might slightly confuse people. Perhaps the easiest is indeed to keep using git master as-is now that's looking and functioning very well. It never hurts to add a small note on the AUR page clarifying the difference between both branches, but that's up to you as developer. Before you know it people might ask for a qmediathekview-interactive-git PKGBUILD :)

**Comment by adamreichold** [comment]
> One nitpick: marking both cargo and rust as makedepends is redundant, either one of those will do.

I am following several official Arch packages, e.g. `cbindgen` or `geckodriver`, here as there are multiple different packages (e.g. `rust` and `rustup` in the official repositories and several others in AUR) providing the various parts of the Rust toolchain.

Hence, I'd prefer to say explicitly that I need `cargo` in addition to `rustc` instead of e.g. calling that directly via another build system like `qmake`.

**Comment by adamreichold** [comment]
Closing this for now as I'll keep the minimum complexity version that is currently `master`.
