### ISSUE TITLE
Add support for sorting columns

### ISSUE THREAD

**Issue by ghost** [adamreichold/QMediathekView#15]
Hi, I wonder if it's possible to add a feature. I miss having the opportunity to `sort` columns (ascending/descending). It would make this feature-complete for me. Nothing urgent though, QMediathekView is working fine.

Enjoy the holiday season, regards.

**Comment by adamreichold** [comment]
The removal was deliberate as the new normalized and compressed representation means that sorting become measurably compared to unsorted queries. But I'll try to make it work so there is no impact in the unsorted case...

**Comment by adamreichold** [comment]
Pushed something to `master` that should do the trick but do note that sorting by the title column is not possible due to it being stored compressed.
