### ISSUE TITLE
Icons are not displayed in the AppImage

### ISSUE THREAD

**Issue by probonopd** [adamreichold/QMediathekView#16]
On Xubuntu bionic:

![](https://user-images.githubusercontent.com/2480569/83939136-ef1ad680-a7c9-11ea-8a8a-c4a329995458.png)

* Used to work e.g., in QMediathekView-4943468-x86_64.AppImage
* Does not work in QMediathekView-45aea73-x86_64.AppImage anymore

Also, 45aea73 shows errors on the command line that 4943468 did not.

Has something changed in how the binary is compiled and packaged?

**Comment by probonopd** [comment]
Seems to be caused by libqgtk3. Workaround:

```
./QMediathekView-45aea73-x86_64.AppImage --appimage-extract
rm squashfs-root/usr/plugins/platformthemes/libqgtk3.so
squashfs-root/AppRun
```

Icons are back!

**Comment by adamreichold** [comment]
> Has something changed in how the binary is compiled and packaged?

Nothing except for adding `libqgtk3` in 892841e1b46f8f543ce24aa343c9b14fa68af3c4 which was necessary on my machine for the AppImage to pick up the system icon theme.

Any suggestions that let me keep the system icon theme support and restore icons for you? Should I explicitly include another platform theme?

**Comment by probonopd** [comment]
Strange, libqgtk3 never (with or without AppImage) worked properly for me, at least not without also having libqgtk2. This is on a Xubuntu machine. I am not sure what is going on here (or how it is even supposed to work.)

**Comment by adamreichold** [comment]
> at least not without also having libqgtk2

So maybe I should include that explicitly as well?

> This is on a Xubuntu machine.

I tested it on an OpenSUSE machine running a KDE desktop and without the plug-in, the AppImage-version would not pick up any icon themes (not even hicolor) installed on the system.

**Comment by probonopd** [comment]
@adamreichold what happens if you do the workaround from https://github.com/adamreichold/QMediathekView/issues/16#issuecomment-640007361 on that system?

**Comment by adamreichold** [comment]
If I remove just this one file, no regression in functionality is visible. I hence pushed a new commit to `master` which removes the platform theme but keeps all icon engines (instead of just SVG) as I guess this was the actual issue on this particular system. Could you give the current continuous build a try whether this solves the issue in your case as well?

**Comment by probonopd** [comment]
Thanks @adamreichold I can confirm that icons are back for me now.
