### ISSUE TITLE
Error adding symbols

### ISSUE THREAD

**Issue by toby63** [adamreichold/QMediathekView#18]
Building with the newest commit is failing with the following error:
`/usr/bin/ld: /usr/lib/libzstd.so.1: error adding symbols: DSO missing from command line`

I use the following AUR package on Manjaro:
https://aur.archlinux.org/packages/qmediathekview-git

Build commands are:
`qmake-qt5`   
` make`

**Comment by toby63** [comment]
It's a problem with the zstd package:
https://bugs.archlinux.org/task/73333

Closing.

**Comment by adamreichold** [comment]
Thanks for taking the time to report this and please re-open if changes are need here after all.

Since I am not using Arch Linux at the moment, I have to admit to having forgotten about that AUR package. Would you by chance be interested in bumping it to use Qt 6 instead of Qt 5? QMediathekView should be compatible with Qt 6 and I am using it on OpenSUSE Tumbleweed for quite a while now.

**Comment by toby63** [comment]
I will take a look at it. 
(btw just noticed that you are also the maintainer on the AUR)

**Comment by adamreichold** [comment]
The diff

```diff
diff --git a/PKGBUILD b/PKGBUILD
index 78aed2b..5c6f885 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -1,15 +1,15 @@
 # Maintainer: Adam Reichold <adam.reichold@t-online.de>
 
 pkgname=qmediathekview-git
-pkgver=r89.0e7fcdb
+pkgver=r131.602a3f4
 pkgrel=1
 pkgdesc='An alternative front-end to the MediathekView database. (development version)'
 arch=('i686' 'x86_64' 'armv7h')
 url='https://github.com/adamreichold/QMediathekView'
 license=('GPL3')
-depends=('qt5-base' 'hicolor-icon-theme')
+depends=('qt6-base' 'hicolor-icon-theme')
 optdepends=('vlc: for direct playback of shows')
-makedepends=('git' 'qt5-tools' 'rust' 'cargo')
+makedepends=('git' 'qt6-tools' 'rust' 'cargo')
 conflicts=('qmediathekview')
 source=('git+https://github.com/adamreichold/QMediathekView.git')
 md5sums=('SKIP')
@@ -23,7 +23,7 @@ pkgver() {
 build() {
   cd "$srcdir/QMediathekView"
 
-  qmake-qt5
+  qmake6
   make
 }
```

brings me at least to the same error message when using an Arch Linux container, but it feels risky pushing this without even a working build...

**Comment by toby63** [comment]
Arch just released a new testing version of zstd (that should fix the Arch Bug [73333](https://bugs.archlinux.org/task/73333) (see also: https://github.com/archlinux/svntogit-packages/commit/be1f696c1d9768393fbf70abe662eec9e51ddb0c)), but the build is still not working:

```
    eingefügt von »findOrInsert« bei /usr/include/qt6/QtCore/qhash.h:640:19,
    eingefügt von »insert.constprop.isra« bei /usr/include/qt6/QtCore/qcache.h:226:37:
/usr/include/qt6/QtCore/qhash.h:553:17: Warnung: Argument 1 Wert »18446744073709551615« übersteigt maximale Objektgröße 9223372036854775807 [-Walloc-size-larger-than=]
  553 |         spans = new Span[nSpans];
      |                 ^
/usr/include/qt6/QtCore/qhash.h: In Elementfunktion »insert.constprop.isra«:
/usr/include/c++/11.2.0/new:128:26: Anmerkung: in einem Aufruf der hier deklarierten Allokationsfunktion »operator new []«
  128 | _GLIBCXX_NODISCARD void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
      |                          ^
/usr/bin/ld: /home/tobias/Stuff/AUR/qmediathekview-git/src/QMediathekView/internals/release/libinternals.a(internals-85ae3c4314dee55f.internals.2797ecfc-cgu.3.rcgu.o): undefined reference to symbol 'ZSTD_getFrameContentSize'
/usr/bin/ld: /usr/lib/libzstd.so.1: error adding symbols: DSO missing from command line
collect2: Fehler: ld gab 1 als Ende-Status zurück
make: *** [Makefile:263: QMediathekView] Fehler 1
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
```

I assume the build works on other systems?

**Comment by adamreichold** [comment]
> I assume the build works on other systems?

I regularly build on OpenSUSE Tumbleweed, but against Qt 6. Could you give the patch from https://github.com/adamreichold/QMediathekView/issues/18#issuecomment-1062227765 a try? Thank you!

**Comment by adamreichold** [comment]
(Just tested this for completeness and Qt 5 build works as well.)

**Comment by adamreichold** [comment]
It also appears to be the case that the updated package is still in testing but not yet core: https://archlinux.org/packages/?sort=&q=zstd&maintainer=&flagged=

**Comment by adamreichold** [comment]
I can reproduce the error in an Arch container using zstd 1.5.2-3 and I think the important point is
```
/usr/bin/ld: /home/builder/src/QMediathekView/internals/release/libinternals.a(internals-85ae3c4314dee55f.internals.2797ecfc-cgu.3.rcgu.o): undefined reference to symbol 'ZSTD_getFrameContentSize'
```
which suggests that Zstd is dynamically linked even though the `zstd-sys` crate should default to static linking AFAIK.

**Comment by toby63** [comment]
Thx for testing and confirming.
How should we proceed from here?
Should I file a bug report somewhere?

**Comment by adamreichold** [comment]
Still trying to figure things out...

**Comment by adamreichold** [comment]
Interestingly, building manually in the same container works...

**Comment by toby63** [comment]
Interesting, then it could be an issue with `makepkg`.

**Comment by adamreichold** [comment]
Another data point: debug builds via `makepkg` work as well.

**Comment by adamreichold** [comment]
And another one: This is not specific to Zstd, i.e. if a do link Zstd dynamically, then it fails with the statically linked LZMA:
```
/usr/bin/ld: /home/builder/pkgbuild/src/QMediathekView/internals/release/libinternals.a(internals-1c44fae8e87a6651.internals.deb2e0a7-cgu.13.rcgu.o): undefined reference to symbol 'lzma_stream_decoder@@XZ_5.0'
/usr/bin/ld: /usr/lib/liblzma.so.5: error adding symbols: DSO missing from command line
```

So it seems that optimized but not debug builds fail to statically link archives under `makepkg`. I think it might certainly be helpful to ask someone more knowledgable about `makepkg` what interaction could trigger this behaviour at this point.

**Comment by adamreichold** [comment]
By now, I can confirm that setting the same compiler flags as `makepkg`, i.e.
```
declare -x CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection"
```
will also trigger the issue when building manually.

**Comment by adamreichold** [comment]
This is getting weird: It appears that it is not the contents of `CFLAGS`, but just the fact that `CFLAGS` is set at all, e.g. via `export CFLAGS=""` that breaks this. But only on Arch Linux, not for example on Tumbleweed.

**Comment by adamreichold** [comment]
It appears that if the environment variable `CFLAGS` is set, no matter what the content is, then `qmake` will use its own compiler flags instead and set that as the environment for the child processes including `cargo` so that the Rust build picks these up via the `cc` crate, i.e. without `CFLAGS` being set
```
[zstd-sys 1.6.3+zstd.1.5.2] CFLAGS = None
[zstd-sys 1.6.3+zstd.1.5.2] running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-fvisibility=hidden" "-DZSTD_LIB_DEPRECATED=0" "-DXXH_PRIVATE_API=" "-DZSTDLIB_VISIBILITY=" "-DZDICTLIB_VISIBILITY=" "-DZSTDERRORLIB_VISIBILITY=" "-o" "/home/builder/build/internals/release/build/zstd-sys-89a31485e416e0cd/out/zstd/lib/dictBuilder/fastcover.o" "-c" "zstd/lib/dictBuilder/fastcover.c"
```
but with `export CFLAGS=""` set
```
[zstd-sys 1.6.3+zstd.1.5.2] CFLAGS = Some("-pipe -O2 -flto -fno-fat-lto-objects -Wall -Wextra -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB")
[zstd-sys 1.6.3+zstd.1.5.2] running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-pipe" "-O2" "-flto" "-fno-fat-lto-objects" "-Wall" "-Wextra" "-D_REENTRANT" "-fPIC" "-DQT_NO_DEBUG" "-DQT_WIDGETS_LIB" "-DQT_GUI_LIB" "-DQT_NETWORK_LIB" "-DQT_CORE_LIB" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-fvisibility=hidden" "-DZSTD_LIB_DEPRECATED=0" "-DXXH_PRIVATE_API=" "-DZSTDLIB_VISIBILITY=" "-DZDICTLIB_VISIBILITY=" "-DZSTDERRORLIB_VISIBILITY=" "-o" "/home/builder/build/internals/release/build/zstd-sys-2bc7cefeec9f77eb/out/zstd/lib/dictBuilder/fastcover.o" "-c" "zstd/lib/dictBuilder/fastcover.c"
```

**Comment by adamreichold** [comment]
This appears to happen on OpenSUSE Tumbleweed as well, it is just that Qt's compiler flags do not include `-flto -fno-fat-lto-objects` there which I suspect is what breaks creating the final `libinternals.a` static archive by `rustc`.

More specifically, I suspect that `rustc` does not handle [GCC's "thin" LTO objects](https://gcc.gnu.org/onlinedocs/gccint/LTO-Overview.html#LTO-Overview) and therefore misses all symbols which are only available as GIMPLE bytecode when linking `libinternals.a`. (One should be able to test this by using Clang for the whole build so that the C compiler and `rustc` use compatible LTO object formats but I am not sure how to convince `qmake6` to do that ATM.)

**Comment by toby63** [comment]
Thx for tracking the problem down.
Famous lto problems, I remember I had of few of those already.
The Arch folk want to enable it everywhere (and already did).

So could we disable the usage of lto in the PKGBUILD file?
Or is the solution more complicated?

**Comment by adamreichold** [comment]
> So could we disable the usage of lto in the PKGBUILD file?

Do you know how to convince `qmake` to not set those flags via the `PKGBUILD`? If so, that would seem to be a reasonable workaround IMHO.

**Comment by adamreichold** [comment]
> > So could we disable the usage of lto in the PKGBUILD file?
> 
> Do you know how to convince `qmake` to not set those flags via the `PKGBUILD`? If so, that would seem to be a reasonable workaround IMHO.

Adding `CONFIG-=ltcg` works for me in the container.

**Comment by adamreichold** [comment]
@toby63 I have uploaded an updated `PKGBUILD`. Could you please give it a try? Thanks!

**Comment by toby63** [comment]
> @toby63 I have uploaded an updated `PKGBUILD`. Could you please give it a try? Thanks!

Just tried the new build, it works.
Thank you very much for taking your time to fix this rather distro specific problem :+1:.
