### ISSUE TITLE
QMediathekView does not show certain entries of Mediathek

### ISSUE THREAD

**Issue by toby63** [adamreichold/QMediathekView#19]
For example I searched for the new ZDF series: "Das Quartett"

Regular MediathekView shows it, but QMediathekView doesn't.

**Comment by adamreichold** [comment]
I suspect that you searched for it using the title instead of the topic field?

![grafik](https://user-images.githubusercontent.com/12997846/157322362-c8e6e29d-2f63-402b-ac88-a47c10ae94b8.png)

**Comment by toby63** [comment]
Yep thats true.
Sry for that, didn't even think about this possibility.

Nevertheless it would be very nice to have some kind of "common" search field for both. What do you think?

**Comment by adamreichold** [comment]
> Nevertheless it would be very nice to have some kind of "common" search field for both. What do you think?

The reason for the current structure is that there is a full-text search index backing the title field, but not topic and channel. Full-text search is generally more resource intensive which is why I would prefer to keep it limited to the single field.
