### ISSUE TITLE
[Feature Request] Update database via cron/systemd timer

### ISSUE THREAD

**Issue by ghost** [adamreichold/QMediathekView#27]
Hi, I wonder if it's possible to enhance QMediathekView with a routine to update the mediathekview database(s)[0][1] via traditional `cron` job and/or `systemd timer`.

[0] https://liste.mediathekview.de/Filmliste-akt.xz
[1] https://liste.mediathekview.de/Filmliste-diff.xz

**Comment by adamreichold** [comment]
The main issue I see is that this would require a CLI/headless way to run the application, i.e. start, update the database and quit. Currently everything is event-based but manually triggering the relevant events should certainly be doable.

Note that QMediathekView writes to the user's home directory, so this would need to be per-user jobs/timers.

Would you be willing to test a pull request implementing this?

**Comment by adamreichold** [comment]
@glitsj16 Could you give the code in #28 a try by running `QMediathekView --headless` from a Cron job/systemd timer?

**Comment by ghost** [comment]
> Currently everything is event-based but manually triggering the relevant events should certainly be doable.

That's promising!

> Note that QMediathekView writes to the user's home directory, so this would need to be per-user jobs/timers.

Agreed. For systemd timers that's not a problem. Just a matter of placing those under /usr/lib/systemd/user instead of /usr/lib/systemd/system or their /etc counterparts. For traditional cron that could easily be done by the user manualy. Personally I use [gnome-schedule](https://gnome-schedule.sourceforge.net) for the latter, but I bet their are similar GUI's for manipulating crontab's for other DE's.

> Would you be willing to test a pull request implementing this?

Absolutely, no problem testing an implementation.

**Comment by ghost** [comment]
@adamreichold

I'll test the code in #28 and report back ASAP. Thank you!

**Comment by ghost** [comment]
@adamreichold The code from #28 does update the database. ~~But it also shows the GUI. Is this intended? I assumed it wouldn't, but I'll do more testing.~~ Anyway, a big thank you for considering and implementing this feature so promptly.

EDIT: cloned the wrong branch argh... When cloning the `cli-update` branch all is fine!

**Comment by ghost** [comment]
These are the per-user systemd timer units I tested with:

```sh
$ cat /etc/systemd/user/mediathekview-dbupdate.service
[Unit]
Description=Update Mediathekview Database
RequiresMountsFor=/home/
Wants=mediathekview-dbupdate.timer

[Service]
Type=oneshot
ExecStart=/usr/bin/QMediathekView --headless
```

```sh
$ cat /etc/systemd/user/mediathekview-dbupdate.timer
[Unit]
Description=Update Mediathekview Database Daily

[Timer]
OnCalendar=daily
AccuracySec=12h
Persistent=true

[Install]
WantedBy=default.target
```

**Comment by adamreichold** [comment]
Note that one can also place these in `$HOME/.config/systemd/user` or rather `$XDG_CONFIG_HOME` if the system-wide locations are not accessible.

**Comment by ghost** [comment]
@adamreichold One final question. Will this feature stay in the `cli-update` branch indefinately or do you plan to integrate it in `master` in the future? I ask because I'm willing to create an AUR package for this. Currently, as you know, the AUR's [qmediathekview-git](https://aur.archlinux.org/packages/qmediathekview-git) won't have the feature.

EDIT: I'm too slow lol, just noticed you took care of this already in https://github.com/adamreichold/QMediathekView/commit/90a29a6d566272edd30c0231d5e93d97f7222ea2. Wunderbar!
