### ISSUE TITLE
Failed to update database: Could not parse data.

### ISSUE THREAD

**Issue by ghost** [adamreichold/QMediathekView#5]
Hi, recently QMediathekView stopped working for me. I've tried clearing preferences settings & database dir without succes.

$ lsb_release -d
Description: Arch Linux

$ pacman -Qi qmediathekview-git | grep Version
Version : r53.21c0213-1

$ pacman -Qi qt5-base | grep Version
Version         : r58.e74e38f-1

$ QMediathekView
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2

In GUI:
Failed to update database: Could not parse data.

**Comment by adamreichold** [comment]
Hello glitsj16,

please retry after rebuilding the package to update to the latest version which should be `r58.e74e38f` which among other things should fix parsing of UTF-16 character escape sequences which have started to appear in the movie lists.

Regards, Adam.

**Comment by ghost** [comment]
Hello Adam,

Thanks for your response. I made a copy/paste error in my prior post. qmediathekview-git is already the latest available git version. That is the version I saw the reported error on. My apologies for the confusion. Did a rebuild anyway but I keep getting the same error. As a test I installed the java based 'mediathek' package from AUR, which works just fine. Anything else I could try?
```

$ pacman -Qi qmediathekview-git | grep Version
Version         : r58.e74e38f-1

$ pacman -Qi qt5-base | grep Version
Version         : 5.7.1-2

$ cat ~/.config/QMediathekView/QMediathekView.conf
[General]
fullListMirrors=http://m.picn.de/f/Filmliste-akt.xz, http://m1.picn.de/f/Filmliste-akt.xz, http://m2.picn.de/f/Filmliste-akt.xz, http://download10.onlinetvrecorder.com/mediathekview/Filmliste-akt.xz, http://mediathekview.jankal.me/Filmliste-akt.xz, http://verteiler1.mediathekview.de/Filmliste-akt.xz, http://verteiler2.mediathekview.de/Filmliste-akt.xz, http://verteiler3.mediathekview.de/Filmliste-akt.xz
mirrorsUpdatedOn=@DateTime(\0\0\0\x10\0\0\0\0\0\0%\x80\xb0\x3\xc1\xec \0)
partialListMirrors=http://m.picn.de/f/Filmliste-diff.xz, http://m1.picn.de/f/Filmliste-diff.xz, http://m2.picn.de/f/Filmliste-diff.xz, http://download10.onlinetvrecorder.com/mediathekview/Filmliste-diff.xz, http://mediathekview.jankal.me/Filmliste-diff.xz, http://verteiler1.mediathekview.de/Filmliste-diff.xz, http://verteiler2.mediathekview.de/Filmliste-diff.xz, http://verteiler3.mediathekview.de/Filmliste-diff.xz

$ QMediathekView
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2

In GUI:
Failed to update database: Could not parse data.

```
Regards, glitsj16.

**Comment by adamreichold** [comment]
Hello again,

it seems the encoding of suffix compression for URL has changed for some listings. I have committed a partial fix (these shows in particular will have valid small and large URL, but the default URL will be nonsense) which can try out by fetching the latest revision.

Regards, Adam.

**Comment by ghost** [comment]
Confirming the latest revision is working great. Thanks for your efforts in fixing this.

Regards, glitsj16.
