### ISSUE TITLE
Make it easy to copy the download link URL

### ISSUE THREAD

**Issue by probonopd** [adamreichold/QMediathekView#7]
Please make it easy to copy the download link URL, e.g., by clicking a "Copy download link(s)" button and selecting the size.

It should be possible to copy multiple download links for more than one episode at once, by selecting multiple ones:

![](https://user-images.githubusercontent.com/2480569/50728221-496bbf80-111e-11e9-9461-8888d3d4f482.png)

**Comment by adamreichold** [comment]
Thank you for taking the time to report this. I have two questions though:
* If multiple shows are selected and the download link is to be copied, what format should the resulting clipboard content have? One line per link? Comma-separated links? Or some more complex MIME type? Or should they be copied one after the other to be picked up clipboard managers?
* Are you aware that you can use an external download manager by specifying a download command in the settings, e.g. I personally use this to interface with a `aria2c` instance via IPC. Would that resolve your use case as well? I am hesitant to add another button to avoid cluttering the UI. Maybe adding context menu would be more suitable?

**Comment by probonopd** [comment]
My use case:
I want to be able to put the links e.g., into an e-mail.

One line per link with no other markup would be ideal.

I could also imagine this format that would copy all resolutions at once:

```
# Low resolution
http://.../...
http://.../...
http://.../...

# Mid resolution
http://.../...
http://.../...
http://.../...

# High resolution
http://.../...
http://.../...
http://.../...
```

**Comment by adamreichold** [comment]
Agreed, plain text and one link per line seems like the best format. But as indicated above, I think I'd prefer putting this into a context menu instead of adding another button to the details panel...

**Comment by adamreichold** [comment]
Could you give 0c6f6f7fc78703e72650d58090b0e916c3a8081a a try and tell me if that works for you?

**Comment by probonopd** [comment]
If the AppImage PR was merged, then I could download it :-)

**Comment by adamreichold** [comment]
> If the AppImage PR was merged, then I could download it :-)

Obviously, but as I said there, I need to learn about this a bit first. But since this being GitHub and such, rebasing your branch should allow you to both the latest changes from master here and the as-of-now unmerged AppImage integration.

**Comment by probonopd** [comment]
Yes, I will give it a try. Thank you

**Comment by probonopd** [comment]
Works perfectly :+1:  Thank you very much.

![works](https://user-images.githubusercontent.com/2480569/50730843-f1997c80-114e-11e9-8f25-2c137f453bbb.png)

If you want to try:
https://github.com/probonopd/QMediathekView/releases

**Comment by probonopd** [comment]
If things progress at this rate, this app should seriously be nominated for the [Grimme Award](https://en.wikipedia.org/wiki/Grimme-Preis). Because it is way better than the sectionalist mess the public TV stations have been producing over all those years.

**Comment by adamreichold** [comment]
> If things progress at this rate, this app should seriously be nominated for the Grimme Award.

Do note that the main work here is that of the [MediathekView project](https://mediathekview.de/) which maintains the scrapers and hosts the database snapshots. This here is just an alternative Qt-based frontend (with rather limited functionality compared to the main application).

**Comment by probonopd** [comment]
I know. That project should have been nominated for the Grimme Award years ago, along with [MediathekViewWeb](https://mediathekviewweb.de/).
